# Generated by Django 5.1.3 on 2024-11-30 17:25

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('invite_code', models.CharField(max_length=6, unique=True)),
                ('activated_invite_code', models.ForeignKey(blank=True, null=True, on_delete=models.SET(users.models.set_invite_code), related_name='invitees', to='users.user', to_field='invite_code')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
