version: "3.9"

services:
  app:
    build: .
    container_name: django_container
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://admin:qwerty@db:5432/users
    depends_on:
      - db
  db:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: users
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d users"]
      interval: 10s
      timeout: 5s
      retries: 5
    # volumes:
    #   - db_data:/var/lib/postgresql/data
# volumes:
#   db_data: